# Generated by Django 5.0.6 on 2024-06-27 17:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('publish', django.db.models.manager.Manager()),
            ],
        ),
    ]
